### ISSUE TITLE
ConcurrentModificationException in Sentry.currentBreadcrumbs

### ISSUE THREAD

**Issue by fab1an** [joshdholtz/Sentry-Android#110]
I'm getting this error now and then:

```
java.util.ConcurrentModificationException: null
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at java.lang.reflect.Method.invoke(Method.java)
    at android.app.ActivityThread.main(ActivityThread.java:5593)
    at android.os.Looper.loop(Looper.java:135)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Handler.handleCallback(Handler.java:739)
    at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
    at mypackage.RequestAdapter$enqueue$1.onResponse(NetworkManager.kt:166)
    at mypackage.SentryLog.captureFailedRetrofitResponse(SentryLog.kt:99)
    at com.joshdholtz.sentry.Sentry.captureEvent(Sentry.java:310)
    at com.joshdholtz.sentry.Sentry.currentBreadcrumbs(Sentry.java:735)
    at java.util.LinkedList$LinkIterator.next(LinkedList.java:124)
```

`captureFailedRetrofitResponse` looks just like this:

```
Sentry.captureEvent(SentryEventBuilder()
    .setMessage(message)
    .setExtra(mapOf(
         "errorBody" to "string"
    )))
```

**Comment by marcomorain** [comment]
Hi @fab1an - Sorry about the crash. I'll take a look into this today.

**Comment by fab1an** [comment]
Great thank you. Maybe you can leverage a [`BlockingQueue`](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/BlockingQueue.html) for this.

**Comment by fab1an** [comment]
Do you need help on this?

**Comment by marcomorain** [comment]
Yes please @fab1an - can you take a look at the approach in https://github.com/joshdholtz/Sentry-Android/pull/111 please? What do you think?

**Comment by fab1an** [comment]
@marcomorain I think the `BlockingQueue` was the wrong idea.

It's probably easiest to use a ReadWriteLock: https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/locks/ReentrantReadWriteLock.html

```java
private final ReentrantReadWriteLock breadcrumbLock = ReentrantReadWriteLock()
```

When reading the list wrap it like this:

```java
try {
   breadcrumbLock.readLock().lock()

   ...use the list ...

} finally {
   breadcrumbLock.readLock().unlock()
}
```

When writing:

```java
try {
   breadcrumbLock.writeLock().lock()

   ...write the list...

} finally {
   breadcrumbLock.writeLock().unlock()
}
```

**Comment by marcomorain** [comment]
Hi @fab1an - I have not had much time to look into this over the holidays.

Can you take a look at PR #111 please? I had not used ReadWriteLocks before, thanks for showing me that pattern.
