### ISSUE TITLE
E/Sentry: Error loading from storage  java.lang.ClassNotFoundException: com.a.a.p

### ISSUE THREAD

**Issue by akramShokri** [joshdholtz/Sentry-Android#130]
Hi
I receive this error log eachtime I initialize sentry:

`09-14 12:28:26.827 8412-8412/come.example.myapp E/Sentry: Error loading from storage
                                                           java.lang.ClassNotFoundException: com.a.a.p
                                                               at java.lang.Class.classForName(Native Method)
                                                               at java.lang.Class.forName(Class.java:308)
                                                               at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:2263)
                                                               at java.io.ObjectInputStream.readNewClassDesc(ObjectInputStream.java:1641)
                                                               at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:657)
                                                               at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1782)
                                                               at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:761)
                                                               at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
                                                               at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
                                                               at java.util.ArrayList.readObject(ArrayList.java:661)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                               at java.io.ObjectInputStream.readObjectForClass(ObjectInputStream.java:1330)
                                                               at java.io.ObjectInputStream.readHierarchy(ObjectInputStream.java:1242)
                                                               at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1835)
                                                               at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:761)
                                                               at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
                                                               at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
                                                               at com.joshdholtz.sentry.Sentry$InternalStorage.readObject(Sentry.java:534)
                                                               at com.joshdholtz.sentry.Sentry$InternalStorage.<init>(Sentry.java:486)
                                                               at com.joshdholtz.sentry.Sentry$InternalStorage.<init>(Sentry.java:463)
                                                               at com.joshdholtz.sentry.Sentry$InternalStorage$LazyHolder.<clinit>(Sentry.java:473)
                                                               at com.joshdholtz.sentry.Sentry$InternalStorage$LazyHolder.access$1300(Sentry.java:472)
                                                               at com.joshdholtz.sentry.Sentry$InternalStorage.getInstance(Sentry.java:469)
                                                               at com.joshdholtz.sentry.Sentry$InternalStorage.access$100(Sentry.java:463)
                                                               at com.joshdholtz.sentry.Sentry.setupUncaughtExceptionHandler(Sentry.java:183)
                                                               at com.joshdholtz.sentry.Sentry.init(Sentry.java:137)
                                                               at com.joshdholtz.sentry.Sentry.init(Sentry.java:115)                                                           come.example.myapp.MainActivity.onCreate(MainActivity.java:75)
                                                               at android.app.Activity.performCreate(Activity.java:5977)
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2258)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
                                                               at android.app.ActivityThread.access$800(ActivityThread.java:148)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:135)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5272)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
                                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "com.a.a.p" on path: DexPathList[[zip file "/data/app/come.example.myapp-1/base.apk" `

**Comment by joshdholtz** [comment]
@akramShokri This library is no longer being supported :blush: Please use the offical sentry library instead - https://github.com/getsentry/sentry-java
