### ISSUE TITLE
ConcurrentModificationException in Sentry.init()

### ISSUE THREAD

**Issue by woostrowski** [joshdholtz/Sentry-Android#54]
java.lang.RuntimeException: Unable to create application com.android.tools.fd.runtime.BootstrapApplication: java.util.ConcurrentModificationException
                                                                           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4643)
                                                                           at android.app.ActivityThread.access$1300(ActivityThread.java:165)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1433)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                           at android.os.Looper.loop(Looper.java:194)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5370)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:525)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                           at dalvik.system.NativeStart.main(Native Method)
                                                                        Caused by: java.util.ConcurrentModificationException
                                                                           at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:569)
                                                                           at com.joshdholtz.sentry.Sentry.sendAllCachedCapturedEvents(Sentry.java:192)
                                                                           at com.joshdholtz.sentry.Sentry.setupUncaughtExceptionHandler(Sentry.java:158)
                                                                           at com.joshdholtz.sentry.Sentry.init(Sentry.java:121)

**Comment by joshdholtz** [comment]
@woostrowski Where are you calling `Sentry.init()`? I need a little more information if you want me to try and debug 😉

**Comment by woostrowski** [comment]
Hi,

I already have a fix for the issue. If you add me as a contributor for few
minutes I could push those changes to separate branch and raise merge
request.

BR
Wojtek



wt., 7.06.2016 o 16:15 użytkownik Josh Holtz <notifications@github.com>
napisał:

> @woostrowski <https://github.com/woostrowski> Where are you calling
> Sentry.init()? I need a little more information if you want me to try and
> debug 😉
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joshdholtz/Sentry-Android/issues/54#issuecomment-224293751>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGTUeB4EmqsGX6RqkUe2GhPTpIAlZnajks5qJX0BgaJpZM4Iv8rk>
> .
>
-- 
Pozdrawiam / Best regards
Wojciech Ostrowski

**Comment by joshdholtz** [comment]
@woostrowski Can you fork the repo and do the pull request? I would gladly take a look at it and merge it in 😊

**Comment by woostrowski** [comment]
Hi,

I've just pushed the newer version of my fix. I also noticed that you're
not parsing self-hosted server port so I added that part too.
Please check those changes and let me know when new version will be
released.

BR
Wojtek


wt., 7.06.2016 o 17:42 użytkownik Josh Holtz <notifications@github.com>
napisał:

> @woostrowski <https://github.com/woostrowski> Can you fork the repo and
> do the pull request? I would gladly take a look at it and merge it in 😊
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joshdholtz/Sentry-Android/issues/54#issuecomment-224322169>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGTUeLn8a96flwXaEsK0ZT-tBaxW8G8qks5qJZF4gaJpZM4Iv8rk>
> .
>
-- 
Pozdrawiam / Best regards
Wojciech Ostrowski

**Comment by joshdholtz** [comment]
Fixed in #55

**Comment by woostrowski** [comment]
Great! Are you planning to release it soon on jcenter?

śr., 8.06.2016 o 15:31 użytkownik Josh Holtz <notifications@github.com>
napisał:

> Fixed in #55 <https://github.com/joshdholtz/Sentry-Android/pull/55>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joshdholtz/Sentry-Android/issues/54#issuecomment-224589262>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGTUeHWEZidV_RtNk6hZyPUBXj8iw-vZks5qJsQugaJpZM4Iv8rk>
> .
>
-- 
Pozdrawiam / Best regards
Wojciech Ostrowski

**Comment by joshdholtz** [comment]
@woostrowski Yup yup! Will be releasing in about an hour 🕒

**Comment by joshdholtz** [comment]
@woostrowski Should be up now - https://bintray.com/joshdholtz/maven/sentry-android/1.4.1/view

**Comment by woostrowski** [comment]
Thanks a lot!

śr., 8.06.2016, 22:02 użytkownik Josh Holtz <notifications@github.com>
napisał:

> @woostrowski <https://github.com/woostrowski> Should be up now -
> https://bintray.com/joshdholtz/maven/sentry-android/1.4.1/view
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joshdholtz/Sentry-Android/issues/54#issuecomment-224710220>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGTUeG0EyJLczsBP01uljZIEe6JlH-a9ks5qJx_FgaJpZM4Iv8rk>
> .
>
-- 
Pozdrawiam / Best regards
Wojciech Ostrowski
